---
title: Test
baseURL: "/"
params:
  palette: blue
  header:
    title: Abhishek
    logo_img: images/logo.png
    has_nav: false
    menu:
      actions:
      - label: Sign Up
        url: "/signup"
  footer:
    logo_img: images/logo_alt.png
    tagline: Demo project
    has_nav: false
    nav_title: Company
    has_social: true
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; Stackbit. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
